config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :users, only: [:create, :show]
  resources :sessions, only: [:new, :create]
  delete "/logout", to: 'sessions#destroy', as: 'logout'
  resources :gifs, only: [:create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gif.rb
class Gif < ApplicationRecord
  validates_uniqueness_of :embed_url, :slug
  has_many :user_gifs
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name, :email, :password
  validates_uniqueness_of :name, :email
  has_secure_password
  enum role: [ :admin, :user ]
  has_many :user_gifs
end

app/models/user_gif.rb
class UserGif < ApplicationRecord
  belongs_to :user
  belongs_to :gif
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :current_admin

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin
    current_user && current_user.role == "admin"
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :logged_in?

  private

    def logged_in?
      unless current_user
        raise ActionController::RoutingError.new('Not Found')
      end
    end

end

app/controllers/gifs_controller.rb
class GifsController < BaseController
  before_action :admin?, only: [:create]

  def create
    results = GiphyService.new.random(params[:search_term])
    gif = Gif.new(slug: results[:slug], embed_url: results[:embed_url])
    if gif.save
      flash[:notice] = "Generated new Gif!"
      redirect_to gifs_path
    else
      flash[:error] = "Something went TERRIBLY wrong!"
      redirect_to root_path
    end
  end

  def index
    @gifs = Gif.all
  end

  private

    def admin?
      unless current_admin
        render status: 404
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if user
      session[:user_id] = user.id
      flash[:notice] = "Welcome #{user.name}."
      redirect_to user_path(user)
    else
      flash[:notice] = "Couldn't log in"
      redirect_to root_path
    end
  end

  def destroy
    flash[:notice] = "Logged out! Smell ya later, #{current_user.name}"
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < BaseController
  before_action :logged_in?, only: [:show]

  def create
    user = User.new(user_params)
    if user.save
      flash[:notice] = "Account Successfully Created."
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "Couldn't Create Account"
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user = User.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gifs/_gif_generator.haml
- if current_admin
  = form_tag '/gifs', class: 'generator-form' do
    = text_field_tag 'search_term'
    = submit_tag 'Generate new Gif!', class: 'generator-submit'

app/views/gifs/index.haml
.gif-index
  - @gifs.each do |gif|
    %div{class: "gif"}
      %iframe{src: gif.embed_url}

app/views/layouts/_nav_bar.haml
- if current_user
  %nav.logged-in
    = link_to "Profile", user_path(current_user)
    = link_to "Gifs", gifs_path
    = link_to "Log out", logout_path, method: :delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gifgenerator</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Cabin|Shrikhand|Work+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <div class="inner-alert">
          <%= value %>
        </div>
      </div>
    <% end %>
    <a href=<%= root_path %> >
      <h2>Super Secret Gif Club</h2>
    </a>
    <%= render '/layouts/nav_bar' %>
    <%= render '/gifs/gif_generator' %>
    <%= yield %>
  </body>
</html>

app/views/users/show.haml
.profile.card
  %h3
    = @user.name
  %hr
  %p
    Current email: 
    = @user.email

app/views/welcome/index.haml
%h3
  = form_for @user do |f|
    = f.text_field :name
    = f.email_field :email
    = f.password_field :password
    = f.submit "Create Account", class: 'sign-up-button'

.login
  %span
    Already a member?
    = link_to "Log in", new_session_path